const domQuestions = [
    {
        id: 1,
        question: 'create new div item from 1..5',
        questionHTML: '',
        winScore: 50,
        hintMinus: 20,
        hint: "click add button five times",
        answer: '',
    },
    {
        id: 2,
        question: 'use master checkbox to select all the checkbox',
        questionHTML: '',
        winScore: 70,
        hintMinus: 25,
        hint: 'click the header checkbox',
        answer: '',
    },
    {
        id: 3,
        question: 'stop the counter while number is between 7 - 10',
        questionHTML: '',
        winScore: 30,
        hintMinus: 10,
        hint: 'click stop once 7 is displayed and stop until 10',
        answer: '',
    },
    {
        id: 4,
        question: 'sort score ascending and descending',
        questionHTML: '',
        winScore: 100,
        hintMinus: 30,
        hint: 'sort conparing numbers',
        answer: '',
    },
    {
        id: 5,
        question: 'toggle to the light theme',
        questionHTML: '',
        winScore: 100,
        hintMinus: 30,
        hint: 'click button to change theme',
        answer: '',
    },
    {
        id: 6,
        question: 'calculate sum of the numbers',
        questionHTML: '',
        winScore: 100,
        hintMinus: 30,
        hint: 'you should enter the number of the sum', 
        answer: '',
    },
]